---
name: "Run ansible-lint"

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  ANSIBLE_ROLES_PATH: ansible/roles

jobs:
  build:
    name: Ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "ansible/playbooks"
