---
name: "Run ansible-lint"

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

jobs:
  build:
    name: Ansible-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetdir:
          - "playbooks"
          - "roles"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "ansible/${{ matrix.targetdir }}"
