---
name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare varfile
        uses: canastro/copy-file-action@master
        with:
          source: "packer/variables.json.example"
          target: "packer/variables.json"

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-var-file=packer/variables.json"
          target: packer/db.json
